#!/bin/sh
#
# getversion - get the librarty version by analyzing its header
#
# Done this way so there's a single point of truth about the version.
#
MAJOR=`sed <pingPlugin_lib.h -n -e "/MAJOR/s/#define PINGPLUGINLIB_MAJOR  *//p"`
MINOR=`sed <pingPlugin_lib.h -n -e "/MINOR/s/#define PINGPLUGINLIB_MINOR  *//p"`
RELEASE=`sed <pingPlugin_lib.h -n -e "/RELEASE/s/#define PINGPLUGINLIB_RELEASE  *//p"`
echo ${MAJOR}.${MINOR}.${RELEASE}
